nodeLinker: node-modules

logFilters:
  # Suppress "has no field" type-checking warnings
  - code: YN0002
    level: discard
  # Suppress "missing peer dependency" warnings
  - code: YN0086
    level: discard
